// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qt6f2ogdB-PzVofrvGT4IRT0jeorY1Y',
    appId: '1:712994084666:web:afad5e1a9a2fd3a2616203',
    messagingSenderId: '712994084666',
    projectId: 'app-flutter-quiz',
    authDomain: 'app-flutter-quiz.firebaseapp.com',
    storageBucket: 'app-flutter-quiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUMZgqRNlVeylMTY3jnNvxEQp5Q_ZT4KE',
    appId: '1:712994084666:android:4414495f089f4639616203',
    messagingSenderId: '712994084666',
    projectId: 'app-flutter-quiz',
    storageBucket: 'app-flutter-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXXvqu0N7XhJk0d87iAETDjcD0rFkNcdA',
    appId: '1:712994084666:ios:a051d22093c4ddc4616203',
    messagingSenderId: '712994084666',
    projectId: 'app-flutter-quiz',
    storageBucket: 'app-flutter-quiz.appspot.com',
    iosBundleId: 'com.example.appFlutterQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXXvqu0N7XhJk0d87iAETDjcD0rFkNcdA',
    appId: '1:712994084666:ios:a051d22093c4ddc4616203',
    messagingSenderId: '712994084666',
    projectId: 'app-flutter-quiz',
    storageBucket: 'app-flutter-quiz.appspot.com',
    iosBundleId: 'com.example.appFlutterQuiz',
  );
}
